config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  get '/d' => 'works#detailview'
  get '/d2' => 'works#detailview_2'
  get '/d3' => 'works#detailview_3'
  get '/d4' => 'works#detailview_4'
  resources :posts, except: [:show] do
    post "/like", to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post 
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    #mount_uploader :image, PostImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  #mount_uploader :avatar, AvatarUploader

  
  def is_Like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy]
    
    def create
        new_comment = Comment.new(content: params[:content],
                                  post_id: params[:post_id],
                                  user_id: current_user.id)
        new_comment.save
        redirect_to :back
    end
    
    def destroy
        @comment.destroy
        redirect_to :back
    end
    
    private
        def check_ownership!
            @comment = Comment.find_by(id: params[:id])
            redirect_to root_path if @comment.user.id != current_user.id
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_toggle
        like = Like.find_by(user_id: current_user.id,
                            post_id: params[:post_id])
        if like.nil?
            Like.create(user_id: current_user.id,
                        post_id: params[:post_id])
        else
            like.destroy
        end
        
        redirect_to :back
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, 
                        content: params[:content],
                        image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end
  
  def update
    @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
    
    @post.content = params[:content]
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    redirect_to root_path if @post.user_id != current_user.id
    
    @post.destroy
    redirect_to root_path
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    def detailview
    end
    
    def detailview_2
    end
    
    def detailview_3
    end
    
    def detailview_4
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Openfeminism</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<!--style-->
  <style>
              /*html 에 style태그로 일단 넣어놓고 html 완료되면 css 파일에 추가.*/
      		.logohome{
      		    margin-top: 10%;
      		}
      		
      		.left-box {
               position: fixed;
               width: 50%;
               overflow: scroll;
               margin-left: 2%;
               margin-right: 4%;
               text-align: center;
            }
             
            .right-box {
               margin-left: 10%;
               text-align: center;
            }
            
            .right-new {
               margin-left: 5%;
               text-align: center;
            }
            
            /*.workshop_main{*/
            /*    margin-left: 10%;*/
            /*}*/
                
            .usermenu {
                    text-align: right;
                    margin-right: 4%;
            }
            
            .cardlist {
                    margin-left: -8%;
                    margin-right: 4%;
                    text-align: left;
            }
            
            .like-align {
                    text-align: right;
                    margin-right: -10%;
            }
            
            .likepos{
      		    text-align: right;
      		}
            
            body {
      				margin: 0 auto;
      				text-align: left;
      			}

  			header {
                  width:64%;
  				margin-top:0;
  				padding-top:0;
  			}
  			header p {
  				font-size:0.76em;line-height:1.5em;padding:0.65em 0;
  			}
  			header h1 {
  				font-size:0.9em; line-height:1.4em;
  			}
  			
  			#thumbnail {
                 margin-left: -20%;
                 width: 100%;
                 height: 100%;
  			}
  			
  			#description {
                text-align: center;
  			}
  			
  			#header {
  				width: 75%;
  				padding:20px;
                  position:fixed;
                  z-index:99990;
                  /*background-color:rgba(255,255,255,0.85);*/
  			}
  			#header .inner {
                  width:64%;
  			}
              .symbol {
                  margin-left:-0.8em;
                  position:relative;
                  z-index: 99999;
              }
  			#main {
  				width: 100%;
  			}
  			p {
  				font-size: 0.76em;
  				width: 80%;
  				margin: 0 auto;
  				padding-bottom: 30px;
  			}
  			#main p {
  				width: 80%;
  				margin: 0 auto;
  				padding-bottom: 10px;
  			}
  			#footer {
                  width: 100%;
  				margin: 0 auto;
                  padding:0;
  				bottom: 0;
  				height:100px;
  				text-align: center;
                  z-index:99998;
                  background:none;
  			}
  			#footer_section{
  				text-align: center;
  				margin: 0 auto;
  				padding: 50px 0;
  			}
  			#footer h2 {
  				text-align: center;
  				margin:0 0 20px;
  				font-size:1.3rem;
  			}
  		</style>
</head>
<body>
<!--leftpage-->
<div class="row">
<div class="col s6">
		<!-- Wrapper -->
		<div class="left-box">
			<div id="wrapper">
					
<div id="logohome">
    <a href="/"><%= image_tag("ofLogo_1.png") %></a>
</div>
<!--오픈페미니즘 안내-->
<h2>THE MORE WE CONNECTED,</br>THE STRONGER WE ARE.</h2>
<p>오픈 페미니즘은 국민대학교 조형대학에 기반한 페미니즘 연구 동아리입니다. 저희는 2016년 9월에 발족하였으며, 현재는 약 60명 정도 되는 구성원들과 함께 합니다. 오픈 페미니즘의 모든 구성원들은 디자인을 전공하는 학부생으로, 페미니즘 이슈에 관심을 가진다는 공통점을 지니고 있습니다.</p>
<!--게시판 안내-->
<h2>TEACH GIRLS BRAVERY,</br>NOT PERFECTION.</h2>
<p>오픈 페미니즘의 활동은 <a href="https://www.ted.com/talks/reshma_saujani_teach_girls_bravery_not_perfection?language=ko">르쉬마 사자니(Reshma Saujani)의 강연</a>에서 영감을 받았습니다. 우리는 완벽한 결과물을 내는데 집중하기보다, 페미니즘적인 관점에서 지금껏 시도되지 않았던 다양한 활동들에 도전해보고자 합니다.
<strong>오른쪽 Ideas 페이지에는 댓글을 통해 오픈 페미니즘이 다루었으면 하는 활동을 제안할수 있습니다.</strong> 제안의 형식은 자유입니다. 어떤 생각이라도 환영합니다. 여러분이 주신 아이디어를 밑거름 삼아 오픈 페미니즘의 활동은 계속됩니다.</p>
<!--오픈소스-->
<h2>OPEN SOURCES</h2>
<p>저희 구성원들이 페미니즘적 관점에서 제작한 컨텐츠들은 누구나 참고, 이용할수 있도록 오픈 소스로서 제공됩니다.</p>
						<ul>
							<li><a href="/d">공간키트(space kit)</li>
							<li><a href="/d2">웰컴키트(Welcome Kit)</a></li>
							<li><a href="/d3">조형전 워크샵(Exhibition)</a></li>
							<li><a href="/d4">시각디자인학과 워크샵(Workshop)</a></li>
						</ul>
				
				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section id="footer_section" style="margin:0 auto!important">
								<!--<h2>contact us</h2>-->
								<ul class="icons">
									<li><a href="mailto:openfeminismkmuvcd@gmail.com"><i class="material-icons">mail_outline</i></a></li>
									<li><a href="https://www.facebook.com/openfeminism/"><i class="material-icons">face</i></a></li>
									<li><a href="https://twitter.com/openfeminismkmu"><i class="material-icons">textsms</i></a></li>
									<!--<li><a href="https://github.com/openfeminism" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>-->
								</ul>
							</section>
							<!--<ul class="copyright" style="margin:30px;">
								<li>&copy; Open Feminism. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>-->
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>
            <script>
            //window height
                function heightChange(){
                    var wHeight = $(window).height();
                    $('#wrapper').css({'height':wHeight+'px'});
                }
                window.onload = heightChange;
                window.onresize = heightChange;
                
            //slide
                var idx = 0;
                var slidemax = 3;
                var width = 25;

                function sliding(add) {
                    idx = idx + add;
                    if(idx < 0) idx = slidemax;
                    else if(idx > slidemax) idx = 0;
                    $('.slides').stop().animate({'left' : -(idx*width)+"%"}, "slow");
                }

                autoslide = setInterval(function() { sliding(1) }, 4000);

                function after() {
                    setTimeout(function() {
                        clearInterval(autoslide);  
                        autoslide = setInterval(function() { sliding(1) }, 4000);
                    }, 2000);
                }

                $('#leftbtn, #rightbtn').click(function() {
                    clearInterval(autoslide);  
                    if($(this).attr('id') == "leftbtn") sliding(-1);
                    else sliding(1);
                    after();
                });
                
                $('.slides').hover(function() {
                    clearInterval(autoslide);  
                    after();
                });

            </script>
</div>
</div>

<!--rightpage-->
<div class="col s6">
    <div class="right-box">
    <!--<nav>-->
      <!--<div class="nav-wrapper">-->
      <section>
      <div class="usermenu">
        <!--<a href="/" class="brand-logo">Ideas</a>-->
        <!--<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>-->
        <!--<ul class="right hide-on-med-and-down">-->
        <ul class="actions">
          <!--<li><a href="#">opensource</a></li>-->
          <% if user_signed_in? %>
          <li><%= current_user.name %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
          <% else %>
          <li><a href="/users/sign_in">log in</a></li>
          <li><a href="/users/sign_up">sign up</a></li>
          <% end %>
        </ul>
        <!--<ul class="side-nav" id="mobile-demo">-->
        <!--  <li><a href="#">opensource</a></li>-->
          <!--<li><a href="badges.html">Components</a></li>-->
          <!--<li><a href="collapsible.html">Javascript</a></li>-->
          <!--<li><a href="mobile.html">Mobile</a></li>-->
        <!--</ul>-->
      </div>
      </section>
    <!--</nav>-->
  <%= yield %>
</div>
</div>
</div>
</body>
</html>

app/views/layouts/generic.html.erb
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<div id="header">
						<div class="inner">
							<!-- Logo -->
								<span class="symbol"><a href="index.html" class="logo"><img src="images/ofLogo.png" alt="" width="64px"/></a></span><!--<span class="title"></span>-->
							 <!--Nav -->
								<nav style="left:0;">
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</div>

				<!-- Menu -->
					<nav id="menu" style="left:0;">
						<h2>OPEN FEMINISM</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="generic_5.html">About us</a></li>
							<li><a href="generic.html">Space Kit</a></li>
							<li><a href="generic_2.html">Welcome Kit</a></li>
							<li><a href="generic_3.html">Exhibition</a></li>
							<li><a href="generic_4.html">Workshop</a></li>
						</ul>
					</nav> 

                <!-- space kit-->
				<div id="space_main">
						<div class="inner" style="padding:130px 0;margin-top:0;padding-top:0;">
							<span class="image main"><img src="images/spacekit.jpeg" alt="" /></span>
							<span class="image main"><img src="images/ghiri_beta_2_night_2-01.png" alt="" /></span>
							<p>Space Kit</p>
							<p>공간 키트는 페미니스트들의 모임을 활성화하기 위한 도구 상자입니다. 이 키트에는 일시적으로 공공장소의 빈 공간을 해킹하여 페미니스트들의 모임 장소로 탈바꿈시키기 위한 도구들이 들어 있습니다. </p>
							<p>어떤 모임이든지 물리적인 공간이 주어지지 않는다면 회원들 간에 친목을 다지기 어려워 집니다. 더욱이 대학은 현실적으로 신생 동아리를 위한 상설 공간이 부족합니다. 그래서 오픈 페미니즘은 '공간 해킹'의 개념에서 착안해, 일시적으로 비는 강의실이나 공공장소를 
							해킹하여 회원들이 교류할수 있는 방법을 고안하게 되었습니다. 공간 키트는 수납합, 전시공간, 테이블로 쓰일수 있으며, 공간 안에는 친목을 다지는데 도움을 주는 물건들이 마련되어 있습니다.</p>
							<section>
									<ul class="actions">
										<li><a href="https://drive.google.com/open?id=0B35f2KNN9ZKHTUp3dlpVRkVrVUE" class="button">details</a>
										</li>
                                <!--download files from googledrive-->
                                        <li><a href="https://drive.google.com/uc?export=download&id=0B35f2KNN9ZKHQUR1WFl4aUR1TkE" class="button">download</a>
                                        </li>
									</ul>
								</section>
						</div>
					</div>
				
				<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<section id="footer_section">
								<!--<h2>contact us</h2>-->
								<ul class="icons">
									<li><a href="mailto:openfeminismkmuvcd@gmail.com" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
									<li><a href="https://www.facebook.com/openfeminism/" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="https://twitter.com/openfeminismkmu" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="https://github.com/openfeminism" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>
								</ul>
							</section>
							<!--<ul class="copyright" style="margin:30px;">
								<li>&copy; Open Feminism. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>-->
						</div>
					</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>
            <script>
            //window height
                function heightChange(){
                    var wHeight = $(window).height();
                    $('#wrapper').css({'height':wHeight+'px'});
                }
                window.onload = heightChange;
                window.onresize = heightChange;
                
            var slideIndex = 1;
                showDivs(slideIndex);
                
                function plusDivs(n) {
                    showDivs(slideIndex  += n);
                }

                function showDivs(n) {
                    var i;
                    var x = document.getElementsByClassName("slides");
                    if  (n > x.length) {slideIndex = 1} 
                    if (n < 1) {slideIndex =  x.length} ;
                    for (i = 0; i < x.length; i++) {
                         x[i].style.display = "none"; 
                    }
                     x[slideIndex-1].style.display = "block"; 
                }
                var myIndex = 0;
                carousel();

                function carousel() {
                    var i;
                    var x = document.getElementsByClassName("slides");
                    for (i = 0; i < x.length; i++) {
                       x[i].style.display = "none";  
                    }
                    myIndex++;
                    if (myIndex > x.length) {myIndex = 1}    
                    x[myIndex-1].style.display = "block";  
                    setTimeout(carousel, 5000);    
                }
            </script>

app/views/posts/_post.html.erb
<div class="card-panel blue-grey lighten-5">
                    <div class="header">
                        <span><%= post.user.name %></span>
                        <span><%= post.created_at %></span>
                        <h2 class="pre-line"><%= post.content %></h2>
                    </div>

                    <div class="card-action">
                      <div class="like-align">
                        <p class="pre-line">관심<%= post.likes.size %>명</p>
                      </div>
                        <% if current_user.is_Like?(post) %>
                            <i class="material-icons">favorite_border<%= link_to "dislike", post_like_path(post), method: "post" %></i>
                        <% else %>
                            <i class="material-icons">favorite<%= link_to "like", post_like_path(post), method: "post" %></i>
                        <% end %>
                        <% if current_user.id == post.user_id %>
                            <%= link_to "delete", post_path(post), method: "delete", class: "left" %>
                            <%= link_to "edit", edit_post_path(post), class: "left" %>
                        <% end %>
                        <!--<%= form_tag post_comments_path(post) do %>-->
                        <!--  <div class="input-field col s9 inline">-->
                        <!--    <%= text_area_tag :content, nil, class: "materialize-textarea", required: true %>-->
                        <!--  </div>-->
                        <!--  <div class="input-field inline">-->
                        <!--    <%= button_tag "댓글", class: "btn-flat" %>-->
                        <!--  </div>-->
                        <!--<% end %>-->
                        <!--<% if post.comments.present? %>-->
                        <!--  <ul class="collection">-->
                        <!--  <% post.comments.each do |comment| %>-->
                        <!--    <li class="collection-item">-->
                        <!--      <span class="title"><%= comment.user.name %></span>-->
                        <!--      <span class="right"><%= comment.created_at %></span>-->
                        <!--      <p class="pre-line"><%= comment.content %></p>-->
                        <!--      <% if comment.user.id == current_user.id %>-->
                        <!--        <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>-->
                        <!--      <% end %>-->
                        <!--    </li>-->
                        <!--  <% end %>-->
                        <!--  </ul>-->
                        <!--<% end %>-->
                    </div>
                     </div>

app/views/posts/edit.html.erb
<!--<div class="container">-->
  <div class="row">
    <div class="card col s12">
      <div class="card-content">
        <div class="card-title">수정하기</div>
        <%= form_tag post_path(@post), method: "patch" do %>
        <input type="hidden" name="id" value="<%=@post.id%>">
          <div class="input-field">
            <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
          </div>

          <div class="input-field">
            <%= button_tag "수정하기", class: "btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<!--</div>-->

app/views/posts/index.html.erb
<!--rightpage-->
<div class="right-new">
<!--<h2>Ideas</h2>-->
<!--<div class="container">-->
  <div class="row">
    <div class="input-field col s12">
      <div class="card-content">
        <!--<%= image_tag("blank.png") %>-->
        <h2>IDEAS</h2>
        <%= form_tag posts_path do %>
          <!--<div class="input-field">-->
          <!--    <%= file_field_tag :image %>-->
          <!--</div>-->
          <div class="input-field">
            <%= text_area_tag :content, nil, class: "materialize-textarea" %>
          </div>

          <div class="input-field">
            <%= button_tag "write", class: "btn-flat" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!--</div>-->
<div class="right-box">
<!--<div class="container">-->
    <div class="row">
     <div class="cardlist">
        <div class="col s12 m12">
        <!--    <div class="card">-->
        <!--        <div class="card-image">-->
        <!--            <img src="http://materializecss.com/images/office.jpg" />-->
        <!--        </div>-->
        <!--        <div class="card-content">-->
        <!--            <div class="card-title"><%= current_user.name %></div>-->
        <!--            <p>이메일 : <%= current_user.email %></p>-->
        <!--            <p>올린 글 개수 : <%= @posts_count %></p>-->
        <!--            <%= link_to new_post_path do %>-->
        <!--                <button class="btn">글 쓰기</button>-->
        <!--            <% end %>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</div>-->
        <div>
            <% @posts.each do |post| %>
                <%= render partial: "post", object: post %>
            <% end %>
        </div>
    </div>
</div>
</div>
</div>

app/views/works/detailview.html.erb
<div class="right-box">
    				<div id="spacekit_main">
    				    <div id="thumbnail">
    				    <%= image_tag("blank.png") %>
    				    <%= image_tag("spacekit_web.jpg") %>
                         <%= image_tag("blank.png") %>
                            <p><strong>Space Kit</strong></p>
							<p>공간 키트는 페미니스트들의 모임을 활성화하기 위한 도구 상자입니다. 이 키트에는 일시적으로 공공장소의 빈 공간을 해킹하여 페미니스트들의 모임 장소로 탈바꿈시키기 위한 도구들이 들어 있습니다. </p>
							<p>어떤 모임이든지 물리적인 공간이 주어지지 않는다면 회원들 간에 친목을 다지기 어려워 집니다. 더욱이 대학은 현실적으로 신생 동아리를 위한 상설 공간이 부족합니다. 그래서 오픈 페미니즘은 '공간 해킹'의 개념에서 착안해, 일시적으로 비는 강의실이나 공공장소를 
							해킹하여 회원들이 교류할수 있는 방법을 고안하게 되었습니다. 공간 키트는 수납합, 전시공간, 테이블로 쓰일수 있으며, 공간 안에는 친목을 다지는데 도움을 주는 물건들이 마련되어 있습니다.</p>
							<section>
									<ul class="actions">
										<li><a href="https://drive.google.com/open?id=0B35f2KNN9ZKHTUp3dlpVRkVrVUE" class="btn-flat">details</a>
										</li>
                                <!--download files from googledrive-->
                                        <li><a href="https://drive.google.com/uc?export=download&id=0B35f2KNN9ZKHQUR1WFl4aUR1TkE" class="btn-flat">download</a>
                                        </li>
									</ul>
								</section>
						</div>
					</div>
</div>

app/views/works/detailview_2.html.erb
<div class="right-box">
    				<div id="welcomekit_main">
    				    <div id="thumbnail">
    				    <%= image_tag("blank.png") %>
                          <%= image_tag("ofweb_wk2-01.png") %>
                         <%= image_tag("blank.png") %>
                            <p><strong>Welcome Kit</strong></p>
							<p>웰컴키트는 국민대학교 조형대학에 새롭게 들어올 학생들에게 배부되는 안내 문서 및 환영 선물 꾸러미입니다. 이 컨텐츠는 신입생들이 공동체 내에 존재하는 가부장적 문화를 인지하고 젠더 감수성을 키울 수 있도록 돕기 위해 제작되었습니다.</p>
							<p>웰컴키트는 성폭력 대응 메뉴얼, 젠더 문제를 다루는 만화, 연결을 주제로 한 뱃지, usb, 페미니즘적 문구를 다룬 레터링 스티커로 구성됩니다.<br>
							메뉴얼은 성폭력이 무엇인지 정의하고, 혹시 모를 불상사가 생겼을때 대응할 수 있는 방법을 소개합니다. 
							만화인 '착한 아이에게는 보이지 않는'은 성적 다양성을 존중하자는 메세지를 담고 있습니다.
							굿즈들은 연결성을 강조하는 형태로 제작되었습니다. 레터링은 참여자 한 사람이 하나의 발언을 선택해 자유롭게 제작했습니다.</p>
							<section>
									<ul class="actions">
										<li><a href="https://drive.google.com/file/d/0B1-YFwrkBAn6YUdhZzI2N0E1ek0/view?usp=sharing" class="btn-flat">details</a>
										</li>
                                <!--download files from googledrive-->
                                        <li><a href="https://drive.google.com/uc?export=download&id=0B35f2KNN9ZKHZ2cyY3l6clZ1bXc" class="btn-flat">download</a>
                                        </li>
                                        <li><a href="http://www.hani.co.kr/arti/PRINT/784879.html" class="btn-flat">featured</a>
                                        </li>
									</ul>
							</section>
						</div>
					</div>
</div>

app/views/works/detailview_3.html.erb
<div class="right-box">
    				<div id="exhibition_main">
    				    <div id="thumbnail">
    				    <%= image_tag("blank.png") %>
                          <%= image_tag("ofweb_ex2-01_1.png") %>
                         <%= image_tag("blank.png") %>
                            <p><strong>조형전 오픈 페미니즘 워크샵</strong></p>
							<p>오픈페미니즘은 2016년 국민대학교 조형대학 조형전을 맞아 조형관 앞에서 페미니즘을 주제로 워크샵 부스를 개설하였습니다.</p>
							<p>부스 안에는 고정적인 성 역할에 대해 다시 생각해보도록 유도하는 단어 게시판과 컬러 저장소가 갖추어져 있었습니다. 오픈 페미니즘의 회원들은 교내외에서 찾아온 방문객들을 맞이하며 페미니즘 이슈에 관해 이야기를 나누었습니다.</p>
							<section>
									<ul class="actions">
										<li><a href="https://drive.google.com/file/d/0B35f2KNN9ZKHWkxRZVBXLS0weUE/view?usp=sharing" class="btn-flat">details</a>
										</li>
									</ul>
							</section>
						</div>
					</div>
</div>

app/views/works/detailview_4.html.erb
<div class="right-box">
    				<div id="workshop_main">
    				    <div id="thumbnail">
    				    <%= image_tag("blank.png") %>
                          <%= image_tag("opentalk.jpg") %>
                         <%= image_tag("blank.png") %>
							<p><strong>시각디자인학과 워크샵</strong></p>
							<p>오픈페미니즘은 소모임으로 자리잡기 전인 2016년 9월에 '오픈 페미니즘 1, 2부'라는 토론 행사를 개최하였습니다. 이 자리는 시각디자인학과 안에서 페미니즘 이슈를 논하기 위해 만들어졌으며, 이후 오픈 페미니즘이 소모임으로 발족되는 계기가 되었습니다.</p>
							<section>
									<ul class="actions">
										<li><a href="https://drive.google.com/open?id=0B35f2KNN9ZKHelpreGtmdWJDelU" class="btn-flat">details</a>
										</li>
									</ul>
							</section>
						</div>
					</div>
</div>